services:

  cassandra:
    image: cassandra:3
    profiles:
      - cdh
    networks:
      - pega24_net
    restart: unless-stopped

  pega:
    image: ${PEGA_RUN_IMAGE}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: ${CONTAINER_NAME}
    environment:
      - JDBC_URL=jdbc:postgresql://${DOCKER_LHOST}:5432/postgres
      - NODE_TYPE
      - NODE_TIER
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
      - EXTERNAL_STREAM
      - STREAM_BOOTSTRAP_SERVERS
      - STREAM_NAME_PATTERN
      - STREAM_SECURITY_PROTOCOL
      - STREAM_SASL_MECHANISM
      - CASSANDRA_CLUSTER
      - CASSANDRA_NODES
      - PEGA_SEARCH_URL=http://pega-srs
 #     - SEARCH_AND_REPORTING_SERVICE_URL=http://pega-srs

    ports:
      - 8080:8080
      
    networks:
      - pega24_net
    restart: unless-stopped

  pega-install:
    image: ${PEGA_INSTALL_IMAGE}
    profiles:
      - install
    environment:
      - ACTION=install
      - SYSTEM_NAME=pegaweb
      - PRODUCTION_LEVEL=2
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://${DOCKER_LHOST}:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega24_net
      
  pega-upgrade:
    image: ${PEGA_UPGRADE_IMAGE}
    profiles:
      - upgrade
    environment:
      - ACTION=upgrade
      - UPGRADE_TYPE=in-place
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://${DOCKER_LHOST}:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
    networks:
      - pega24_net

volumes:
  pgdata:
  
networks:
  pega24_net:
    name: pega_common
    external: true